### ISSUE TITLE
Modifying the "lended" state on existing item doesn't have any effect

### ISSUE THREAD

**Issue by FelixWohlfrom** [temporaerhaus/inventory-wiki#16]
If you accidentally create an item with wrong "lended" state, it is not possible to fix this later.
I.e. you can edit the "lended" state in the ui after creation, but once you save the changes, they are not persisted.
This might lead to unwanted items in the inventory list.

(And in our scenario, we where not even able to delete the accidentally created inventory item due to missing rights).

**Comment by ech0-de** [comment]
this is partially on purpose, since changing the lended state requires to be renamed, and hence the label to be reprinted. I hid the checkbox from the edit dialog to prevent confusion, but for now the underlying issue won't be fixed.

If this happens again add a "delete me" suffix to the item title and create a new label with the correct information 😅
